---
title: "Hidden Markov model for movement data in Ecology"
author: "MP Etienne"
format: html
toc: true
date: last-modified
date-format: "[Dernière Mise à jour] Octobre 2024"
css: mpe_pres_revealjs.css
execute: 
  freeze: auto
---


## Course description 

Hidden Markov Models are a powerful class of statistical models that are particularly well-suited to analyzing sequential data, where observed patterns are influenced by underlying, unobservable (hidden) states. 

In this course, we will explore the basic concepts linked with  Hidden Markov Models (HMM):

* Definition
* Inference with partially observed data - EM algortihm
* Baum Welch Algortihm, EM algorithm in the context of HMM
* Viterbi algorithm to reconstruct Hidden states



## The lab session

In ecological research, HMMs have gained prominence for their ability to extract meaningful behavioral states from movement data, such as distinguishing between foraging, resting, and traveling in animals.

We will apply the HMM concepts to analyze movement of animals and we will focus on   Masked Booby (Sula dactylatra) as case studies ([Data available here](donnees_fous.txt)). 

The data used in this lab were collected through the work of Sophie Bertrand (IRD), Guilherme Tavares (UFRGS), Christophe Barbraud, and Karine Delord (CNRS) and i would like to thank the International Associated Young Team (JEAI) IRD Tabasco for providing access to these data.

